### ISSUE TITLE
Planetshine does not get a config file/directory when installed with JNSQ on CKAN

### ISSUE THREAD

**Issue by CaribeanSoul** [Galileo88/JNSQ#12]
I installed JNSQ through CKAN and planetshine was added either as a dependency or a recommended mod.  When I installed like this CKAN did not make me install the planetshine default config package.  Without that package the GameData/PlanetShine/Config directory is not created and the planetshine setting.cfg file is not installed anywhere.  I am fairly certain this is why my planetshine config settings never save between game sessions.  (Please note I'm talking about the user settings from the settings window in-game, not the planetary body settings.)

**Comment by Galileo88** [comment]
Fixed, and CKAN will be updated soon
