### ISSUE TITLE
Bad install message is incorrect

### ISSUE THREAD

**Issue by linuxgurugamer** [Galileo88/JNSQ#15]
Hey, just wanted to let you know, that I cloned the entire JNSQ repo, and then copied the two directories in the GameData  directory (JNSQ and RationalResources) into my game, now getting a message saying that it's been installed incorrectly.  Getting the following dialog:

![KSP_x64_2020-02-02_18-27-21](https://user-images.githubusercontent.com/1630166/73617154-bf747b80-45e9-11ea-9edc-ef7dd1737d8a.png)

This is a screenshot of the JNSQ directory where the version file it:
![explorer_2020-02-02_18-29-30](https://user-images.githubusercontent.com/1630166/73617194-15e1ba00-45ea-11ea-8689-1a92a73a0cee.png)

**Comment by linuxgurugamer** [comment]
The problem is in the .version files, in the INSTALL_LOC stanza.
You have:
	"INSTALL_LOC":
	{
		"NAME": "JNSQ",
		"PATH": "JNSQ/Version/JNSQ.version"
	}
but the PATH cannot have the file there.  YOu can do one of the following:

	"INSTALL_LOC":
	{
		"NAME": "JNSQ",
		"PATH": "",
		"DIRECTORY": "JNSQ/Version/",
		"FILE": "JNSQ.version"
	}

or:
	"INSTALL_LOC":
	{
		"NAME": "JNSQ",
		"PATH": "",
		"FILE": "JNSQ/Version/JNSQ.version"
	}

**Comment by Galileo88** [comment]
Ok coolio. i made the change.

**Comment by linuxgurugamer** [comment]
Please let JadeOfMaar know, the same problem is with RationalResources (at least the RR which came with JNSQ)
