### ISSUE TITLE
RemoteTech antenna ranges

### ISSUE THREAD

**Issue by armegeddon** [Galileo88/JNSQ#17]
With RT installed, the ranges for passive, omni, and dish antenna are not multiplied by the Antenna.cfg due to RT deleting the ModuleDataTranmitter and replacing it with ModuleRTAntenna. The following is the MM patch that will scale all the antenna, including integrated ones. 

```
@PART:HAS[@MODULE[ModuleRTAntenna*]]:LAST[JNSQ]
{	
	@MODULE[ModuleRTAntenna*]
	{
		@OmniRange *= 4
		@Mode1OmniRange *= 4
		@Mode1DishRange *= 4
		%JNSQ = True
	}
}

@PART:HAS[@MODULE[ModuleRTAntenna*]]:LAST[JNSQ]
{
	@MODULE[ModuleRTAntenna*]:HAS[~JNSQ[True]]
	{
		%JNSQ = False
	}
}

```

**Comment by JadeOfMaar** [comment]
Thanks very much. :) Added in [this commit](https://github.com/Galileo88/JNSQ/commit/0751f323413da6dd5f3e2e30f9b4948adc67eb43).
