### ISSUE TITLE
CKAN installation of FinalFrontier ribbons

### ISSUE THREAD

**Issue by HebaruSan** [Galileo88/JNSQ#18]
CKAN currently doesn't install the JNSQ_FinalFrontier.zip ribbon pack. I have started a module for it in KSP-CKAN/NetKAN#7669, but it is not merged yet pending discussion with the JNSQ team.

- The main JNSQ module is set up with a metanetkan; would the team prefer the ribbons to also have a metanetkan? Or is the above PR OK?
- Once JNSQ-RibbonPack is indexed, the main JNSQ should suggest it instead of FinalFrontier so the ribbons are installed
- Is the license the same as the main download?

Tags to ensure notifications: @OhioBob @JadeOfMaar @Galileo88

**Comment by Galileo88** [comment]
@HebaruSan that PR is fine by me
