### ISSUE TITLE
Kerbal Health patch

### ISSUE THREAD

**Issue by GarwelGarwel** [Galileo88/JNSQ#20]
Hey guys, I have recently changed the config structure for Kerbal Health. All the configs must be inside the KERBALHEALTH_CONFIG node. I [fixed and copied your patch over to the Kerbal Health distribution](https://github.com/GarwelGarwel/KerbalHealth/blob/master/GameData/KerbalHealth/Patches/KHJNSQ.cfg) for now to prevent things from breaking. Please decide if you want to update and maintain the config on your end or I keep it on mine (and then you should your patch is redundant). I can submit a PR if you want.

**Comment by Galileo88** [comment]
Hey and thanks for the heads up! I all for it being maintained on your end if you are willing to do that. That will insure that its always up to date.

**Comment by JadeOfMaar** [comment]
PR was merged. o7
