### ISSUE TITLE
Rover Spawn sites

### ISSUE THREAD

**Issue by armegeddon** [Galileo88/JNSQ#23]
All of the MedVehicleSpawn.cfg in the AirBase***A folders use the same LaunchSiteName of "AirBase S05A Rover Spawn" in their LaunchSite definition, instead of the name of their individual group. This causes KK to launch from the S05A spawnpoint, even if it hasn't been opened yet when any of them are selected.

**Comment by JadeOfMaar** [comment]
Thanks for noticing. I lost a bunch of things for the KK update fo JNSQ 0.9... I now know I lost quite a lot of things...

**Comment by armegeddon** [comment]
Didn't notice it originally, but some of the heliport spawn have the same issue. Appears to be only those configs that contain two launchsite entries. The first one is correct, but the second one is set to S05A

**Comment by JadeOfMaar** [comment]
Thanks for that too. I just took care of it.
