### ISSUE TITLE
Checkered terrain on kerbin

### ISSUE THREAD

**Issue by aihaw** [Galileo88/JNSQ#28]
Hi! I'm not sure if it's a JNSQ or a kopernicus bug but there's a chechering that happens on terrain both during flights or on the KSC. Here are some screenshots:
![screenshot58](https://user-images.githubusercontent.com/16972795/83928104-e1942b00-a78e-11ea-8f72-8e0930c2bee0.png)
![screenshot60](https://user-images.githubusercontent.com/16972795/83928107-e35dee80-a78e-11ea-9443-e55f4f6f9ab1.png)
![screenshot57](https://user-images.githubusercontent.com/16972795/83928109-e3f68500-a78e-11ea-8f95-3b5244979c5e.png)
Anyway, besides that the mod is the most gorgeous planet pack out here! You're bringing KSP2-like visual content (or at least as it should be).

**Comment by aihaw** [comment]
![screenshot61](https://user-images.githubusercontent.com/16972795/83928690-e4901b00-a790-11ea-9022-5509f2b33c8a.png)

**Comment by JadeOfMaar** [comment]
That's normal. It's a fault of the terrain shaders. It's a fault of KSP, not any mods. Be careful when it starts happening. It's generally eventually followed by your VRAM filling completely and KSP crashing.

**Comment by aihaw** [comment]
Thank you for being so fast!

**Comment by JadeOfMaar** [comment]
:D
