### ISSUE TITLE
Fix height of space high above Kerbin

### ISSUE THREAD

**Issue by norcalplanner** [Galileo88/JNSQ#3]
Both Rocket and I show that the boundary between space low and space high is 250 km ASL.  I hear that it's supposed to be at 800 km due to the larger size of 2.7x Kerbin.

**Comment by norcalplanner** [comment]
Nevermind - this turned out to be a conflict caused by Celestial Body Science Editor, which is a dependency for Probes Before Crew. Everything is fine once I removed that mod.

**Comment by JadeOfMaar** [comment]
Wow! 😁 Congrats on spotting it. That's a great find.
