### ISSUE TITLE
Minmus/Mun science multiplier imbalanced with Principia

### ISSUE THREAD

**Issue by apricot-azumi** [Galileo88/JNSQ#33]
## Background
- Minmus needs much lower Δv to land or brake into orbit than the Mun.
- With Principia installed, Minmus is made nearer to Kerbin than the Mun.
- However, science multipliers is not tweaked.

## Problem
Mun science is not appealing at all with the modified orbits for Principia.

## Suggestion
Consider also rebalancing science multipliers for modified Minmus/Mun.

**Comment by JadeOfMaar** [comment]
This has been taken care of by @OhioBob. Minmus science values reduced.
