### ISSUE TITLE
Vessel shadow visible in far distance

### ISSUE THREAD

**Issue by 4x4cheesecake** [Galileo88/JNSQ#4]
The shadow of a vessel is visible on the surface of Kerbin at any altitude within the atmosphere. Haven't tried other planets yet.

![screenshot4](https://user-images.githubusercontent.com/40007416/58923000-f08c6b80-873d-11e9-8d7a-433c6fbd7c9c.png)
![screenshot3](https://user-images.githubusercontent.com/40007416/58923006-f5511f80-873d-11e9-81d9-bdbe7a989d09.png)
![screenshot5](https://user-images.githubusercontent.com/40007416/58923045-2893ae80-873e-11e9-8cc6-c3ec5f12cb2c.png)

Second shadow comes from the decoupled engine+tank before reentry.

KSP: 1.7.0 + MH DLC

Installed mods:
- ClickThroughBlocker
- CTTP
- EditorExtensionsRedux
- EVE
- JNSQ
- KER
- KJR
- Kopernicus
- MissingHistory
- MFI
- PreciseManeuver
- RealisticResources
- scatterer
- SigmaReplacementsSkyBox

MM ConfigCache:
[ModuleManager.zip](https://github.com/Galileo88/JNSQ/files/3255054/ModuleManager.zip)

Log:
[output_log.zip](https://github.com/Galileo88/JNSQ/files/3255057/output_log.zip)

edit: Did another test on the Mun. The shadow becomes visible at 90km ASL (if you know where to look) and gets bigger and clearly visible at 85km ASL:

![screenshot8](https://user-images.githubusercontent.com/40007416/58924207-49123780-8743-11e9-9235-a45ede41e2ba.png)

**Comment by norcalplanner** [comment]
I like it. Maybe make it smaller and/or more diffuse when an atmosphere is present.

**Comment by 4x4cheesecake** [comment]
> I like it. Maybe make it smaller and/or more diffuse when an atmosphere is present.

It doesn't look right at all and I doubt this happens on purpose.

**Comment by Galileo88** [comment]
Have you tried to see if it happens without Scatterer?

**Comment by Galileo88** [comment]
Whoops didn’t mean to close it lol

**Comment by 4x4cheesecake** [comment]
> Have you tried to see if it happens without Scatterer?

Just tried it and it's indeed caused by scatterer. Apparently this issue is not specific to JNSQ, it also appears in a stock game but neither me nor anyone else noticed it so far^^
Played around with the scatterer settings and this seem to be caused by the terrain shadows. Disabled them and the shadows fade out/in around 2.5km ASL.

I'll shift the issue over to scatterer :) 

> Whoops didn’t mean to close it lol

Feel free to close it now but you may want to consider to disable the terrain shadows in the scatterer config of JNSQ ;)
