### ISSUE TITLE
Floating Monolith next to the KSC

### ISSUE THREAD

**Issue by 4x4cheesecake** [Galileo88/JNSQ#5]
The Monolith next to the KSC is floating a few meters in the air:

![screenshot6](https://user-images.githubusercontent.com/40007416/58923661-d7d18500-8740-11e9-9cb5-c8207ebc3035.png)

Same install as described in #4 ;)

**Comment by Galileo88** [comment]
Fixed in 0.5 :)

**Comment by infoman** [comment]
That UFO thing at the ice cap also floats in the air in 0.7
