### ISSUE TITLE
Oceanic Icebergs Near the KSC

### ISSUE THREAD

**Issue by Vatruvius** [Galileo88/JNSQ#51]
I do not know if this is an issue with JNSQ or Spectra, but if I fly over the ocean next to the KSC, icebergs pop into view and cover the water, which feels out of place.
![screenshot2](https://user-images.githubusercontent.com/44359446/230261968-420b40b1-4fde-4d5c-b8ee-4f393eda0365.png)
![screenshot7](https://user-images.githubusercontent.com/44359446/230261977-9331cc9e-efdf-49c9-9a1b-2d50c1576d10.png)

**Comment by Vatruvius** [comment]
I removed Spectra and still have these icebergs floating near the KSC. Landing in the water shows the icebergs as 3D models, not just effects. Is there a way to disable them?

**Comment by KaidKM3** [comment]
That ice is Parallax. Parallax Brings Life to All stock planets. And adds Ice to Laythe and the Polar regions of Kerbin.

**Comment by Vatruvius** [comment]
> That ice is Parallax. Parallax Brings Planets to Life, adding rocks, Crystals, Plants, and more. it also adds Ice around Laythe and the Polar regions of Kerbin.

Thank you, @KaidKM3, for clarifying the icebergs are coming from parallax. Is it normal for them to appear this close to the KSC? It just feels weird, is all. I would expect to see icebergs near the poles.

**Comment by KaidKM3** [comment]
The icebergs near the KSC is something i dont understand Ive installed it too a while ago to test to see if its the same way and it is. it might be JNSQ making Parallax put icebergs Globally, I Really do not know. Unless The JNSQ Devs say something about Parallax that could give us an answer to why there is global Icebergs. Best to just deal with it for now.

**Comment by KaidKM3** [comment]
Mightve Found a fix.
https://github.com/coldrifting/JNSQ_ParallaxScatters

Apparently JNSQ is incompatible with Parallax.
The link is a Compatability Patch for JNSQ and Parallax.

**Comment by KaidKM3** [comment]
> > That ice is Parallax. Parallax Brings Planets to Life, adding rocks, Crystals, Plants, and more. it also adds Ice around Laythe and the Polar regions of Kerbin.
> 
> Thank you, @KaidKM3, for clarifying the icebergs are coming from parallax. Is it normal for them to appear this close to the KSC? It just feels weird, is all. I would expect to see icebergs near the poles.

I do not believe you recieved the post i made in march. hopefully this will ping you to see the post about a fix with a parallax incompatability within JNSQ.

**Comment by Vatruvius** [comment]
@KaidKM3, thank you for the reply. I haven't played in a while, but I will add the link to my mod list next I play. Thanks again.
