### ISSUE TITLE
TweakChute interferes with chute MM QoL patches

### ISSUE THREAD

**Issue by Jognt** [Galileo88/JNSQ#8]
There are parachute QoL MM patches floating around to set the deploy pressure slider to the desired value by default (so you don't have to adjust every parachute).

This value is minAirPressureToOpen which TweakChute uses to determine the _slider_ minimum setting.

I recommend using clampMinAirPressureToOpen instead as my limited testing showed that that is the value that determines what the minimum value for the slider itself is for stock parachutes.

**Comment by Sigma88** [comment]
@OhioBob  thoughts?

**Comment by OhioBob** [comment]
No change to be made at this time.
